server:
  port: 4004

spring:
  cloud:
    gateway:
      routes:
        ## http://localhost:4004/api/patients/** -> http://patient-service:4000/patients/**
        - id: patient-service-route
          uri: http://patient-service:4000
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1

        ## http://localhost:4004/api-docs/patients -> http://patient-service:4000/v3/api-docs
        - id: api-docx-patient-route
          uri: http://patient-service:4000
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients, /v3/api-docs

        ## http://localhost:4004/api/auth/** -> http://auth-service:4005/auth/**
        - id: auth-service-route
          uri: http://auth-service:4005
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
